name: Ruby

on:
  push:
    branches: ['master', 'dev', 'feature/*']
  pull_request:
    branches: ['master', 'dev', 'feature/*']

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run linters
        run: |
          bundle exec rubocop 


  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 3.0.4

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
